In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
path_1 = "yellow_tripdata_2022-01.csv"

In [3]:
df = pd.read_csv(path_1, low_memory=False)

In [4]:
df.head()

1  2022-01-01 00:35:40  2022-01-01 00:53:29  2.0    3.8  1.0  N  142  236  \
0  1  2022-01-01 00:33:43  2022-01-01 00:42:07  1.0   2.10  1.0  N  236   42   
1  2  2022-01-01 00:53:21  2022-01-01 01:02:19  1.0   0.97  1.0  N  166  166   
2  2  2022-01-01 00:25:21  2022-01-01 00:35:23  1.0   1.09  1.0  N  114   68   
3  2  2022-01-01 00:36:48  2022-01-01 01:14:20  1.0   4.30  1.0  N   68  163   
4  1  2022-01-01 00:40:15  2022-01-01 01:09:48  1.0  10.30  1.0  N  138  161   

   1.1  14.5  3.0  0.5   3.65   0.0  0.3  21.95  2.5  0.0.1  
0    1   8.0  0.5  0.5   4.00  0.00  0.3  13.30  0.0    0.0  
1    1   7.5  0.5  0.5   1.76  0.00  0.3  10.56  0.0    0.0  
2    2   8.0  0.5  0.5   0.00  0.00  0.3  11.80  2.5    0.0  
3    1  23.5  0.5  0.5   3.00  0.00  0.3  30.30  2.5    0.0  
4    1  33.0  3.0  0.5  13.00  6.55  0.3  56.35  2.5    0.0

In [5]:
df.shape

(2463930, 19)

In [6]:
df['1'].unique()

array([1, 2, 6, 5], dtype=int64)

In [7]:
df['1'].value_counts()

2    1716059
1     742272
6       5563
5         36
Name: 1, dtype: int64

In [8]:
x = list(df.columns)
x

['1',
 '2022-01-01 00:35:40',
 '2022-01-01 00:53:29',
 '2.0',
 '3.8',
 '1.0',
 'N',
 '142',
 '236',
 '1.1',
 '14.5',
 '3.0',
 '0.5',
 '3.65',
 '0.0',
 '0.3',
 '21.95',
 '2.5',
 '0.0.1']

In [11]:
df['1.0'].unique()

array([ 1.,  2.,  5.,  3.,  4., 99.,  6., nan])

In [14]:
x = ['2022-01-01 00:35:40', '2022-01-01 00:53:29','1.0',
       'N','14.5', '3.0', '0.5', '3.65',
       '0.0', '0.3', '2.5', '0.0.1', '1', '3.8', '2.0']
# For yellow_trip

In [15]:
x

['2022-01-01 00:35:40',
 '2022-01-01 00:53:29',
 '1.0',
 'N',
 '14.5',
 '3.0',
 '0.5',
 '3.65',
 '0.0',
 '0.3',
 '2.5',
 '0.0.1',
 '1',
 '3.8',
 '2.0']

In [16]:
df = df.drop(x,axis=1)

In [17]:
df.head()

142  236  1.1  21.95
0  236   42    1  13.30
1  166  166    1  10.56
2  114   68    2  11.80
3   68  163    1  30.30
4  138  161    1  56.35

In [18]:
# For Yellow_Trip 
df.rename(columns = {'1.1': 'Passenger_count', '142': 'Pickup_Location', 
                     '236': 'Dropoff_Location', '21.95': 'Fare'}, inplace = True)
df

Pickup_Location  Dropoff_Location  Passenger_count   Fare
0                    236                42                1  13.30
1                    166               166                1  10.56
2                    114                68                2  11.80
3                     68               163                1  30.30
4                    138               161                1  56.35
...                  ...               ...              ...    ...
2463925               90               170                0  13.69
2463926              107                75                0  24.45
2463927              113               246                0  16.52
2463928              148               164                0  15.70
2463929              186               181                0  35.06

[2463930 rows x 4 columns]

In [20]:
df.shape

(2463930, 4)

In [21]:
for col in df:
    print(col, df[col].unique(), "\n")

Pickup_Location [236 166 114  68 138 233 238 141 234 246  43 239 148 237   7 107 263 161
  79 170 162   4 262 249 132 137  90  45  70  48 211 113 164  50 142 265
  88 186 144 224  95  24 158  74 140 163  75 229 209 264 219 232 151 256
 231  87 116  65 188  42  13  33  41 220 146 100 261 125 152 127 143 243
  66 260 181 195 112 129  10 226  25 255 244  12 168 230 189  97  82 190
  52  49  61 145 223 202 228 179  36  40 159  80  17 167 208  69 254 213
 193  77  37 225 171 106  93 247 165 117 212 250  14 157 198  83 169 136
 217 173 123 160   3   1  76  89  22  39  86  18  28 252 227 135  91 124
  38 216 119 205  81 122 194  92 133  35 134 177 215 147 248  63  47 210
 197 201 131 200  56   5 130 191  85 218  51  46 149 241 139 235  71 102
  62 174  72 182  11  29 183  67 155  54 196   8 175  55  53  64 180  34
  60 120  44 257  78 207 242 184 153 185  15  19  26 258 121  57 203 101
 126 128 154 206  23 192  21 108  96  94 259  16   9 178   6 222  98 221
 150  73  20  32  31  58  27 245 21

In [22]:
df = df.dropna()

In [23]:
df.shape

(2463930, 4)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2463930 entries, 0 to 2463929
Data columns (total 4 columns):
 #   Column            Dtype  
---  ------            -----  
 0   Pickup_Location   int64  
 1   Dropoff_Location  int64  
 2   Passenger_count   int64  
 3   Fare              float64
dtypes: float64(1), int64(3)
memory usage: 75.2 MB


In [25]:
df.describe()

Pickup_Location  Dropoff_Location  Passenger_count          Fare
count     2.463930e+06      2.463930e+06     2.463930e+06  2.463930e+06
mean      1.660768e+02      1.635807e+02     1.194449e+00  1.916937e+01
std       6.546807e+01      7.079016e+01     5.001779e-01  2.559641e+02
min       1.000000e+00      1.000000e+00     0.000000e+00 -4.803000e+02
25%       1.320000e+02      1.130000e+02     1.000000e+00  1.130000e+01
50%       1.620000e+02      1.620000e+02     1.000000e+00  1.469000e+01
75%       2.340000e+02      2.360000e+02     1.000000e+00  2.002000e+01
max       2.650000e+02      2.650000e+02     5.000000e+00  4.010956e+05

In [26]:
df.Passenger_count.unique()

array([1, 2, 4, 3, 5, 0], dtype=int64)

In [27]:
df.loc[df['Passenger_count'] == 0]

Pickup_Location  Dropoff_Location  Passenger_count   Fare
2392427               68               246                0  18.25
2392428              257               223                0  55.72
2392429              143               236                0  20.04
2392430              143               262                0  21.21
2392431              239               166                0  21.75
...                  ...               ...              ...    ...
2463925               90               170                0  13.69
2463926              107                75                0  24.45
2463927              113               246                0  16.52
2463928              148               164                0  15.70
2463929              186               181                0  35.06

[71503 rows x 4 columns]

In [28]:
ind = df.loc[df['Passenger_count'] == 0].index
df.drop(ind , inplace=True)

In [29]:
df.Passenger_count.unique()

array([1, 2, 4, 3, 5], dtype=int64)

In [30]:
df.count()

Pickup_Location     2392427
Dropoff_Location    2392427
Passenger_count     2392427
Fare                2392427
dtype: int64

In [31]:
df.Pickup_Location.nunique()

256

In [32]:
df.Dropoff_Location.nunique()

261

In [33]:
for col in df:
    print(col, df[col].unique(), "\n")

Pickup_Location [236 166 114  68 138 233 238 141 234 246  43 239 148 237   7 107 263 161
  79 170 162   4 262 249 132 137  90  45  70  48 211 113 164  50 142 265
  88 186 144 224  95  24 158  74 140 163  75 229 209 264 219 232 151 256
 231  87 116  65 188  42  13  33  41 220 146 100 261 125 152 127 143 243
  66 260 181 195 112 129  10 226  25 255 244  12 168 230 189  97  82 190
  52  49  61 145 223 202 228 179  36  40 159  80  17 167 208  69 254 213
 193  77  37 225 171 106  93 247 165 117 212 250  14 157 198  83 169 136
 217 173 123 160   3   1  76  89  22  39  86  18  28 252 227 135  91 124
  38 216 119 205  81 122 194  92 133  35 134 177 215 147 248  63  47 210
 197 201 131 200  56   5 130 191  85 218  51  46 149 241 139 235  71 102
  62 174  72 182  11  29 183  67 155  54 196   8 175  55  53  64 180  34
  60 120  44 257  78 207 242 184 153 185  15  19  26 258 121  57 203 101
 126 128 154 206  23 192  21 108  96  94 259  16   9 178   6 222  98 221
 150  73  20  32  31  58  27 245 21

In [34]:
df.shape

(2392427, 4)

In [35]:
df.loc[df['Fare'] < 0]

Pickup_Location  Dropoff_Location  Passenger_count   Fare
153                  132               265                4 -23.55
520                  152                48                4 -20.80
522                   50               265                2 -77.80
579                   90               234                2  -7.80
713                   13               246                4 -15.80
...                  ...               ...              ...    ...
2392068              186               186                4  -7.30
2392212              249                79                4 -10.30
2392249               90                90                4  -6.80
2392292               50                48                4  -7.30
2392336              141                24                4 -15.80

[12897 rows x 4 columns]

In [36]:
ind = df.loc[df['Fare'] < 0].index
df.drop(ind , inplace=True)

In [37]:
df.shape

(2379530, 4)

In [38]:
df.loc[df['Fare'] < 0]

Empty DataFrame
Columns: [Pickup_Location, Dropoff_Location, Passenger_count, Fare]
Index: []

In [39]:
df.Pickup_Location.nunique()

256

In [40]:
df.Dropoff_Location.nunique()

261

In [41]:
df.Fare.sum()

45719103.43999997

In [42]:
x = df['Pickup_Location'].value_counts()
x

237    119057
236    117603
132    102419
161     86491
186     79317
        ...  
59          1
27          1
105         1
176         1
115         1
Name: Pickup_Location, Length: 256, dtype: int64

In [43]:
# for yellow trip
x_1 = x.head(10)
x_1

237    119057
236    117603
132    102419
161     86491
186     79317
142     78065
141     75125
48      74575
170     73532
162     73122
Name: Pickup_Location, dtype: int64

In [45]:
x.sum()

2379530

In [46]:
df[df['Pickup_Location'] == 132].Passenger_count

37         1
39         2
40         1
47         1
48         1
          ..
2392371    1
2392372    2
2392373    1
2392397    1
2392413    2
Name: Passenger_count, Length: 102419, dtype: int64

In [47]:
df[df['Pickup_Location'] == 132].Passenger_count.sum()

134240

In [1]:
# considering Demand and Supply as symmetric. We will take average of Pickup cabs at a location and Dropoff cabs at same location.

In [49]:
df[(df['Pickup_Location'] == 237) & (df['Dropoff_Location'] == 237)].value_counts()

Pickup_Location  Dropoff_Location  Passenger_count  Fare 
237              237               1                9.96     534
                                                    9.36     482
                                                    10.56    469
                                   2                7.80     457
                                                    8.30     433
                                                            ... 
                                   1                21.19      1
                                                    21.23      1
                                                    21.60      1
                                                    21.78      1
                                   4                59.80      1
Length: 526, dtype: int64

In [50]:
x_1

237    119057
236    117603
132    102419
161     86491
186     79317
142     78065
141     75125
48      74575
170     73532
162     73122
Name: Pickup_Location, dtype: int64

In [51]:
dict(x_1)

{237: 119057,
 236: 117603,
 132: 102419,
 161: 86491,
 186: 79317,
 142: 78065,
 141: 75125,
 48: 74575,
 170: 73532,
 162: 73122}

In [52]:
# previous logic when we thought that Demand is consisted of the passengers
'''demand = {}
for j in x_1.index:
    demand[j] = df[df['Pickup_Location'] == j].Passenger_count.sum()

temp = sorted(demand.items(), key=lambda f:f[1], reverse=True)
temp = dict(temp)
demand = temp'''

"demand = {}\nfor j in x_1.index:\n    demand[j] = df[df['Pickup_Location'] == j].Passenger_count.sum()\n\ntemp = sorted(demand.items(), key=lambda f:f[1], reverse=True)\ntemp = dict(temp)\ndemand = temp"

In [53]:
# New logic, in which we just take the cars as the demand
demand = dict(x_1)

In [54]:
demand

{237: 119057,
 236: 117603,
 132: 102419,
 161: 86491,
 186: 79317,
 142: 78065,
 141: 75125,
 48: 74575,
 170: 73532,
 162: 73122}

In [55]:
y = df['Dropoff_Location'].value_counts()
y

236    120023
237    103632
141     76175
239     72693
161     72577
        ...  
187        10
204         8
2           5
105         2
99          1
Name: Dropoff_Location, Length: 261, dtype: int64

In [57]:
x.index

Int64Index([237, 236, 132, 161, 186, 142, 141,  48, 170, 162,
            ...
            245,   2, 214, 206, 172,  59,  27, 105, 176, 115],
           dtype='int64', length=256)

In [59]:
df[(df['Pickup_Location'] == 166) & (df['Dropoff_Location'] == 95)]

Pickup_Location  Dropoff_Location  Passenger_count   Fare
51268                166                95                1  45.35
591107               166                95                2  41.30
723524               166                95                1  50.00
1472983              166                95                2  45.80

In [60]:
y[97]

2827

In [61]:
df.loc[df['Dropoff_Location'] == 97]

Pickup_Location  Dropoff_Location  Passenger_count   Fare
109                  233                97                1  29.76
776                   13                97                1  24.96
1386                 132                97                1  63.65
2690                 249                97                1  21.84
2726                 209                97                1  19.80
...                  ...               ...              ...    ...
2391605              170                97                1  32.80
2391887              186                97                1  42.25
2391918               65                97                2   7.30
2392151              132                97                1  59.81
2392203              107                97                1  21.38

[2827 rows x 4 columns]

In [64]:
y[74]

20070

In [65]:
# for yellow trip
y_1 = y.head(10)
y_1

236    120023
237    103632
141     76175
239     72693
161     72577
170     71648
142     68296
48      66119
238     63475
263     59181
Name: Dropoff_Location, dtype: int64

In [66]:
# for yellow trip
round((y[237] + x[237])/2)

111344

In [67]:
# for yellow trip
# this is the symmetric demand and supply
dm_sp = {}
for i in x.index:
    temp = round((y[i] + x[i])/2)
    dm_sp[i] = temp
#print(dm_sp)
temp = sorted(dm_sp.items(), key=lambda f:f[1], reverse=True)
temp = dict(temp)
dm_sp = temp
dm_sp

{236: 118813,
 237: 111344,
 161: 79534,
 141: 75650,
 142: 73180,
 239: 72762,
 170: 72590,
 48: 70347,
 162: 64410,
 186: 63090,
 230: 61374,
 238: 60549,
 132: 60076,
 263: 59810,
 140: 58702,
 234: 58459,
 79: 57374,
 163: 57372,
 68: 56616,
 229: 54949,
 107: 54828,
 249: 47171,
 164: 44562,
 262: 39780,
 90: 38569,
 138: 37481,
 137: 36850,
 143: 36781,
 43: 35497,
 100: 34770,
 233: 32888,
 246: 32708,
 113: 30144,
 231: 29490,
 75: 28950,
 114: 25659,
 151: 25351,
 50: 21858,
 148: 20865,
 264: 20251,
 144: 18788,
 158: 18336,
 211: 17220,
 166: 15194,
 74: 13711,
 41: 12741,
 87: 11589,
 13: 11509,
 125: 9802,
 24: 9152,
 261: 8450,
 42: 7156,
 224: 7034,
 232: 7016,
 4: 6343,
 88: 5410,
 244: 5199,
 7: 5020,
 70: 5008,
 116: 4766,
 145: 4694,
 265: 4204,
 45: 3946,
 209: 3904,
 226: 3683,
 33: 3252,
 152: 3110,
 181: 2842,
 255: 2723,
 256: 2714,
 243: 2460,
 112: 2402,
 223: 2252,
 129: 2211,
 1: 2010,
 25: 1934,
 146: 1932,
 65: 1922,
 61: 1896,
 193: 1874,
 179: 1725,
 97:

In [69]:
x_1

237    119057
236    117603
132    102419
161     86491
186     79317
142     78065
141     75125
48      74575
170     73532
162     73122
Name: Pickup_Location, dtype: int64

In [72]:
# taking top 10 locations
temp = {}
cnt = 0
for i in dm_sp:
    cnt += 1
    if cnt > 10:
        break
    else:
        temp[i] = dm_sp[i]
dm_sp = temp   
dm_sp   

{236: 118813,
 237: 111344,
 161: 79534,
 141: 75650,
 142: 73180,
 239: 72762,
 170: 72590,
 48: 70347,
 162: 64410,
 186: 63090}

In [73]:
temp = sorted(dm_sp.items(), key=lambda f:f[1], reverse=True)
temp = dict(temp)
dm_sp = temp
dm_sp

{236: 118813,
 237: 111344,
 161: 79534,
 141: 75650,
 142: 73180,
 239: 72762,
 170: 72590,
 48: 70347,
 162: 64410,
 186: 63090}

In [74]:
# These are the top 10 locations
for i in dm_sp:
    print(i)

236
237
161
141
142
239
170
48
162
186


In [75]:
cost_matrix = {} #{Row: Column}
temp_2 = []
for i in dm_sp:
    temp = {}
    #temp_2 = []
    for j in dm_sp:
        #print(i,j)
        temp[j] = df.loc[(df['Pickup_Location'] == i) & (df['Dropoff_Location'] == j)].Fare.mean()
        #temp_2.append(df.loc[(df['Pickup_Location'] == i) & (df['Dropoff_Location'] == j)].Fare.sum())
        #print(temp)
    cost_matrix[i] = temp
    #print(cost_matrix)
cost_matrix

{236: {236: 10.638030662124528,
  237: 12.257933774833642,
  161: 15.657458256030221,
  141: 12.685652846535284,
  142: 15.301967479675172,
  239: 13.230947027764113,
  170: 18.688371859296424,
  48: 18.878950617283788,
  162: 15.216397990911624,
  186: 21.947662061636397},
 237: {236: 11.60614685885125,
  237: 10.701926946817503,
  161: 11.99720842861861,
  141: 10.771728760446155,
  142: 13.103976595275242,
  239: 14.920300153925368,
  170: 14.188690437601391,
  48: 15.439523506988362,
  162: 11.566849951597666,
  186: 17.836765873015647},
 161: {236: 15.322200561995642,
  237: 12.009473510480797,
  161: 12.513746345029054,
  141: 13.874979681150466,
  142: 13.72346687211087,
  239: 16.956265601597433,
  170: 11.66308195592269,
  48: 12.463729557239494,
  162: 10.654867944070258,
  186: 13.056966183574923},
 141: {236: 11.584888947647391,
  237: 10.64983507109044,
  161: 14.03258813770203,
  141: 10.858952306489856,
  142: 14.762624584717422,
  239: 15.796712166171917,
  170: 15.0568

In [76]:
data = pd.DataFrame(cost_matrix)

In [77]:
data

236        237        161        141        142        239  \
236  10.638031  11.606147  15.322201  11.584889  15.606655  13.538226   
237  12.257934  10.701927  12.009474  10.649835  12.920020  14.825676   
161  15.657458  11.997208  12.513746  14.032588  13.245771  16.570402   
141  12.685653  10.771729  13.874980  10.858952  14.834485  15.784124   
142  15.301967  13.103977  13.723467  14.762625  11.713690  10.884910   
239  13.230947  14.920300  16.956266  15.796712  11.247352  11.091440   
170  18.688372  14.188690  11.663082  15.056879  17.223594  20.659655   
48   18.878951  15.439524  12.463730  17.237994  11.054534  13.888744   
162  15.216398  11.566850  10.654868  12.783667  14.452226  18.035971   
186  21.947662  17.836766  13.056966  19.687052  15.218659  19.001712   

           170        48         162        186  
236  17.657660  18.258914  14.711256  21.413763  
237  14.118694  14.645904  11.611937  17.831964  
161  11.416456  11.407823  10.654006  12.690330  
141  14.515443  16.408689  12.097014  19.374927  
142  17.415982  11.124469  15.315336  15.558106  
239  20.754599  13.844356  18.293604  18.932280  
170  12.241599  14.168197  11.130246  12.561125  
48   14.421569  12.132104  13.543527  12.051522  
162  11.197533  13.130971  12.465720  14.676570  
186  12.408421  12.057530  14.238971  16.930078

In [78]:
data.dropna()

236        237        161        141        142        239  \
236  10.638031  11.606147  15.322201  11.584889  15.606655  13.538226   
237  12.257934  10.701927  12.009474  10.649835  12.920020  14.825676   
161  15.657458  11.997208  12.513746  14.032588  13.245771  16.570402   
141  12.685653  10.771729  13.874980  10.858952  14.834485  15.784124   
142  15.301967  13.103977  13.723467  14.762625  11.713690  10.884910   
239  13.230947  14.920300  16.956266  15.796712  11.247352  11.091440   
170  18.688372  14.188690  11.663082  15.056879  17.223594  20.659655   
48   18.878951  15.439524  12.463730  17.237994  11.054534  13.888744   
162  15.216398  11.566850  10.654868  12.783667  14.452226  18.035971   
186  21.947662  17.836766  13.056966  19.687052  15.218659  19.001712   

           170        48         162        186  
236  17.657660  18.258914  14.711256  21.413763  
237  14.118694  14.645904  11.611937  17.831964  
161  11.416456  11.407823  10.654006  12.690330  
141  14.515443  16.408689  12.097014  19.374927  
142  17.415982  11.124469  15.315336  15.558106  
239  20.754599  13.844356  18.293604  18.932280  
170  12.241599  14.168197  11.130246  12.561125  
48   14.421569  12.132104  13.543527  12.051522  
162  11.197533  13.130971  12.465720  14.676570  
186  12.408421  12.057530  14.238971  16.930078

In [79]:
data.to_csv('Cost Matrix.csv', index=True)

In [80]:
df.loc[(df['Dropoff_Location'] == 95)]['Pickup_Location'].unique()

array([141, 234,  87, 132,  68, 161, 138, 162, 229, 114, 148,  95,  48,
         7, 163, 230, 164, 186,  36, 107, 137, 239, 211, 264,  70,  50,
       158, 237,  83, 249, 166, 263, 233,  79,  42, 142, 170, 236, 256,
       140, 143, 260, 196, 129, 174,  90, 261, 102, 135,  13, 179,  93,
        88, 226, 246, 100,  43,  92, 113,  41,  61, 145, 231, 125, 151,
        18,  29,  24,  75, 223, 175, 262, 124,  82, 209,  63, 191, 238,
       144, 119, 232, 198, 149,  56,  21, 130,  28, 134, 197,  76, 212,
       146, 244, 116, 259, 157,  38,  52,  16, 160,  86,  91, 203, 215,
        72,  17,  65, 131], dtype=int64)

In [81]:
x_1

237    119057
236    117603
132    102419
161     86491
186     79317
142     78065
141     75125
48      74575
170     73532
162     73122
Name: Pickup_Location, dtype: int64

In [82]:
df_dm_sm = pd.DataFrame.from_dict(dm_sp, orient='index', columns=['Avg Taxis'])
df_dm_sm .index.name = 'LocationID'
df_dm_sm .reset_index(inplace=True)
df_dm_sm

LocationID  Avg Taxis
0         236     118813
1         237     111344
2         161      79534
3         141      75650
4         142      73180
5         239      72762
6         170      72590
7          48      70347
8         162      64410
9         186      63090

In [83]:
df_dm_sm.head(10)

LocationID  Avg Taxis
0         236     118813
1         237     111344
2         161      79534
3         141      75650
4         142      73180
5         239      72762
6         170      72590
7          48      70347
8         162      64410
9         186      63090

In [84]:
# df_dm_sm.to_csv('Symmetric Demand and Supply_Yellow_Trip.csv', index=True)

In [85]:
df_dm_sm.to_csv('Symmetric Demand and Supply_Green_Trip.csv', index=True)